REGIONS = {
    "poland": ["Warszawa", "Krakow_Centrum", "Gdansk", "Wroclaw", "Poznan", "Szczecin"],
    "poland_south": ["Krakow_Centrum", "Tarnow", "Nowy_Sacz", "Zakopane", "Katowice", "Rzeszow"],
    "poland_north": ["Gdansk", "Gdynia", "Sopot", "Suwalki", "Olsztyn", "Elblag"],
    "poland_central": ["Warszawa", "Lodz", "Radom", "Plock", "Wloclawek"],
    "poland_west": ["Poznan", "Szczecin", "Zielona_Gora", "Gorzow_Wlkp", "Leszno"],
    "poland_east": ["Lublin", "Bialystok", "Zamosc", "Przemysl", "Terespol"],

    "usa_states": {
        "Alabama": "Birmingham",
        "Alaska": "Anchorage",
        "Arizona": "Phoenix",
        "Arkansas": "Little_Rock",
        "California": "Los_Angeles",
        "Colorado": "Denver",
        "Connecticut": "Hartford",
        "Delaware": "Wilmington",
        "Florida": "Miami",
        "Georgia": "Atlanta",
        "Hawaii": "Honolulu",
        "Idaho": "Boise",
        "Illinois": "Chicago",
        "Indiana": "Indianapolis",
        "Iowa": "Des_Moines",
        "Kansas": "Wichita",
        "Kentucky": "Louisville",
        "Louisiana": "New_Orleans",
        "Maine": "Portland_ME",
        "Maryland": "Baltimore",
        "Massachusetts": "Boston",
        "Michigan": "Detroit",
        "Minnesota": "Minneapolis",
        "Mississippi": "Jackson",
        "Missouri": "St_Louis",
        "Montana": "Billings",
        "Nebraska": "Omaha",
        "Nevada": "Las_Vegas",
        "New_Hampshire": "Manchester",
        "New_Jersey": "Newark",
        "New_Mexico": "Albuquerque",
        "New_York": "New_York_City",
        "North_Carolina": "Charlotte",
        "North_Dakota": "Fargo",
        "Ohio": "Columbus",
        "Oklahoma": "Oklahoma_City",
        "Oregon": "Portland_OR",
        "Pennsylvania": "Philadelphia",
        "Rhode_Island": "Providence",
        "South_Carolina": "Charleston",
        "South_Dakota": "Sioux_Falls",
        "Tennessee": "Nashville",
        "Texas": "Houston",
        "Utah": "Salt_Lake_City",
        "Vermont": "Burlington",
        "Virginia": "Richmond",
        "Washington": "Seattle",
        "West_Virginia": "Charleston_WV",
        "Wisconsin": "Milwaukee",
        "Wyoming": "Cheyenne"
    }
}
